compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]

kv_namespaces = [
 { binding = "TEST", id = "815e0b5a177643c093797d43337efa0e", preview_id = "815e0b5a177643c093797d43337efa0e"  }
]